### ISSUE TITLE
Doesn't work with KeeWeb KeePassHTTP Plugin

### ISSUE THREAD

**Issue by subdavis** [RoelVB/ChromeKeePass#1]
Hey there!  

I just tested this out, and I'm unable to get it working with KeeWeb's HTTP plugin.  I tested the same with ChromeIPass, which works fine.  If I pop open the background page, I see a message about:

`POST localhost:19445 empty response`

Let me know if I can help debug further.

**Comment by RoelVB** [comment]
Thanks you for the report. I was unaware of KeeWeb having a HTTP plugin.
I'll look into this.

**Comment by RoelVB** [comment]
Just released a new version which works with KeeWeb.
If you still experience any problems, please let me know.
