### ISSUE TITLE
Plugin stopped working

### ISSUE THREAD

**Issue by GuentherK** [RoelVB/ChromeKeePass#10]
The plugin stopped working with last Edge  (Chromium) update to version 81.0.396.0. The plugin still works with current Chrome Version Version 79.0.3945.130.

Status is _Something went wrong... is KeePass running and is the KeePassHttp plugin installed?_

**Comment by RoelVB** [comment]
Thank you for reporting the issue.
How did you get version 81? I always get version 80.

**Comment by GuentherK** [comment]
I am using the dev version. if that is the reason for the bug feel free to close the issue and I'll report the issue to MS

**Comment by RoelVB** [comment]
I would like to close the issue for now.
If the same problem appears in Edge's bèta channel I will investigate this.

**Comment by GuentherK** [comment]
FYI: As of today with version 81.0.403.1 the bug is fixed, seems like it was a browser bug, thanks for investigating
