### ISSUE TITLE
A list of accounts slowly appears when focusing on the field, login or password.

### ISSUE THREAD

**Issue by f1h0** [RoelVB/ChromeKeePass#101]
The latest version of the application has an interesting updated graphical interface. However, I'm asking the developers to improve the speed of the application, especially when focusing on login and password input fields and when there are multiple accounts on one site. The previous version was more agile in displaying the additional list of accounts when the input field was clicked. The new application requires multiple page updates to display the list, which slows down communication with the application. 

**Application result**
I suggest improving the ability to focus on login and password input fields for quick access to the list of available accounts.

**Comment by RoelVB** [comment]
I'm unable to reproduce this.
Would it be possible to make a screen recording showing the issue?

**Comment by RoelVB** [comment]
Do you mean when you initially load a page CKP will not show any logins and after reloading the page it does show them?
I have seen this behavior in some specific cases and was able to create a fix for it (not yet released).

**Comment by f1h0** [comment]
> Do you mean when you initially load a page CKP will not show any logins and after reloading the page it does show them? I have seen this behavior in some specific cases and was able to create a fix for it (not yet released).

Yes all right you described the situation is exactly as it happens page is loaded initially nothing happens in the fields. refresh again the page two or three times and more then begin to appear loaded data in ChromeKeePass ?is it possible to fix?

**Comment by RoelVB** [comment]
A fix is currently pushed to the bèta release in the stores.
Once approved it will stay in bèta a few week, before it's pushed to the normal/stable release.
