### ISSUE TITLE
how to make chromekeepass automatically not ask for permissions in keepass

### ISSUE THREAD

**Issue by UriZafrir** [RoelVB/ChromeKeePass#102]
Hi 
how to can I make chromekeepass automatically not ask for permissions in keepass?
Thanks in advance.

**Comment by RoelVB** [comment]
I assume you're looking for this KeePassHttp option inside KeePass:
<img width="305" alt="image" src="https://github.com/RoelVB/ChromeKeePass/assets/10999128/9efba6de-411d-41aa-865d-06d2bfdc87f5">

**Comment by UriZafrir** [comment]
great thank you so much!
