### ISSUE TITLE
if the function allows you to add passwords and usernames when the URL is like chrome-extension://egjidjbpglichdc.....

### ISSUE THREAD

**Issue by f1h0** [RoelVB/ChromeKeePass#103]
I have a task to use the **ChromeKeePass** application. Is it possible to configure it when the first address contains the Chrome application?

**Comment by RoelVB** [comment]
Lets see if I understand what you're trying to say?!
You want ChromeKeePass to enter credentials into another extension's settings page or something?

**Comment by f1h0** [comment]
> Lets see if I understand what you're trying to say?! You want ChromeKeePass to enter credentials into another extension's settings page or something?

I want to use your application in order not to drive manually. there are such applications in Chrome that require password input necessary authentication.

**Comment by RoelVB** [comment]
Chrome does not support this.
It only supports URLs with `http:`, `https:` and `file:` (so not `chrome-extension:`). [Docs](https://developer.chrome.com/docs/extensions/develop/concepts/match-patterns)
