### ISSUE TITLE
The "Show ChromeKeePass icon in username/password fields"-Setting doens't work

### ISSUE THREAD

**Issue by STAINCABLER** [RoelVB/ChromeKeePass#104]
I switched the switch off, reloaded the login page, reloaded the browser, reinstalled the extension, rebooted the computer, but nothing seems to make the setting work... :[
The Icon won't disappear.

I'm on Chrome, Version 122.0.6261.129 (Official Build) (64-Bit) and ChromeKeePass version: 2.1.0
If it Matters: KeePass Version 2.56 (64-Bit)

Thanks for your work here, I really like this extension.
Hope you can fix it.

**Comment by RoelVB** [comment]
Thanks for reporting.
This is indeed a bug. I'm going fix it.

**Comment by RoelVB** [comment]
Will be fixed in the next update
