### ISSUE TITLE
Multiple database support

### ISSUE THREAD

**Issue by Argevollen** [RoelVB/ChromeKeePass#106]
When using several databases, the extension becomes very inconvenient to use, because each time you need to connect to the database.

**Comment by RoelVB** [comment]
I guess you're looking for this option in KeePassHttp?
<img width="307" alt="image" src="https://github.com/RoelVB/ChromeKeePass/assets/10999128/63f76e04-d6dc-4a54-bc48-d52ec183acfa">

When you enable this and have multiple databases open (in a single KeePass instance), ChromeKeePass will show entries from all databases.

**Comment by Argevollen** [comment]
Thank you
