### ISSUE TITLE
[BUG] CSS:zoom will cause the position of the account selection box to be offset

### ISSUE THREAD

**Issue by Maxwelline** [RoelVB/ChromeKeePass#108]
When the BODY element of the page is zoomed using the CSS:zoom style, the coordinate offset will appear in the pop-up selection box when clicking on the account input element. As shown in the picture:

![screenshot_2024-06-30_01-11-42](https://github.com/RoelVB/ChromeKeePass/assets/13521166/608fec54-e3d5-4c20-bcff-eaa6122f2b50)

Please fix it, thanks!

**Comment by RoelVB** [comment]
What's you use case here? Did you encounter a site using CSS `zoom` or do you inject it somehow?

The position issue is because the CKP dropdown is mounted outside of the `<body>`. Mounting it inside the body causes multiple other issues.

**Comment by Maxwelline** [comment]
I added the following code through Violentmonkey and visited https://greasyfork.org/en/users/sign_in. I will find that the coordinates of the dropdown triggered by the input are wrong. Because the original size of the entire page changes due to zoom, the coordinates and dimensions in the original content_script.js are obtained before zooming, so they are offset.

**Code**:
```js
// ==UserScript==
// @name        New script greasyfork.org
// @namespace   Violentmonkey Scripts
// @match       https://greasyfork.org/en/users/sign_in*
// @grant       GM_addStyle
// @version     1.0
// @author      -
// @description 2024/7/2 21:48:21
// ==/UserScript==

GM_addStyle(`:root body{zoom:1.5!important;}`);
```

**Screenshot**:
![error](https://github.com/RoelVB/ChromeKeePass/assets/13521166/0ed71069-d3b6-4483-a4f8-b14446f5d383)

Since I did not find the source code of `content_script.js` in the source code, I can only modify the code directly locally and load the modified extension through `load unpacked`. The effect is as follows:

![screenshot_2024-07-02_20-52-46](https://github.com/RoelVB/ChromeKeePass/assets/13521166/b8335c85-8211-4c49-90d6-1886dcd6a6a8)

![fixed](https://github.com/RoelVB/ChromeKeePass/assets/13521166/aaa6661e-0914-499a-bfac-d614e7429566)

Since the relevant source code cannot be found, these simple corrections in the screenshots only fix the offset of the coordinates, but problems such as the size of the dropdown and the scrolling of the screen still exist.

**Comment by RoelVB** [comment]
When you put the `zoom` on the `<html>`-tag instead of `<body>`-tag you will achieve the same thing without breaking CKP.

**Comment by Maxwelline** [comment]
> When you put the `zoom` on the `<html>`-tag instead of `<body>`-tag you will achieve the same thing without breaking CKP.

That doesn't solve the problem, the offset is still there.

![error](https://github.com/RoelVB/ChromeKeePass/assets/13521166/c9d7e792-868a-4a3a-8be5-a74ce53f2a7e)

If you don't have time to fix this bug, you can open source the content_script.js part and I'll Pull requests.

**Comment by Maxwelline** [comment]
I changed the code in the following three places, thus fixing the dropdown position offset, and scroll offset after applying CSS:zoom styles to BODY, and it doesn't affect the case where CSS:zoom is not applied, perfect fix.
### section1
![1](https://github.com/RoelVB/ChromeKeePass/assets/13521166/15982cb1-464a-4e96-af18-95293fd2dd51)
### section2
![2](https://github.com/RoelVB/ChromeKeePass/assets/13521166/0a34b957-bfa4-4863-95b0-7f735297be22)
### section3
![3](https://github.com/RoelVB/ChromeKeePass/assets/13521166/7a497da5-212e-407c-b4a3-faa98726c7e6)
### body css zoom
![screenshot_2024-07-03_22-58-33](https://github.com/RoelVB/ChromeKeePass/assets/13521166/c9ed0362-7c08-49e3-9a59-42f55cf5b0b6)
### fixed
![screenshot_2024-07-03_22-59-28](https://github.com/RoelVB/ChromeKeePass/assets/13521166/fe12df60-0550-4f32-ad20-f35f9bec3059)

Since I don't have the source code, I can only modify it directly on the compiled code. If there is no problem with this fix, please add it to the source code, thanks.

**Comment by RoelVB** [comment]
To clarify. All of CKP is opensource. [this is the entrypoint for the content_script](https://github.com/RoelVB/ChromeKeePass/blob/dev-v2/src/content_script.ts).

For the dropdown positioning [MUI Popper](https://mui.com/material-ui/react-popper/) is used, which uses [Popper.js](https://popper.js.org/).
There is a preview component, [MUI Popup](https://mui.com/base-ui/react-popup/), which uses [Floating UI](https://floating-ui.com/) for positioning. I tried it, but still having the same issue.

It's pretty unclear what you've changed in your "fix", but it seems like you just append the dropdown to the body instead. In [my first comment](https://github.com/RoelVB/ChromeKeePass/issues/108#issuecomment-2200763618) I mentioned that would fix your specific issue, but will create others.

**Comment by Maxwelline** [comment]
> It's pretty unclear what you've changed in your "fix", but it seems like you just append the dropdown to the body instead.

Because css:zoom changes the coordinate system of the page, the script must be corrected to obtain the correct value when obtaining the scroll height. There are two main modifications I mentioned in the screenshot above: 

1. Inserting dropdown into the Body to unify the coordinate system; 
2. Corrected the coordinates of {x,y} of dropdown (correction on the scrollX, scrollY)

Well, modifying third-party library to solve this problem seems more complicated. My ability is limited, so I would like to fix the css:zoom problem by modifying the locally compiled extension file and then loading the extension folder with `load unpacked`. After all, this solves all the problems I encountered.

Thanks for your reply anyway.

**Comment by Maxwelline** [comment]
> For the dropdown positioning [MUI Popper](https://mui.com/material-ui/react-popper/) is used, which uses [Popper.js](https://popper.js.org/). 
> There is a preview component, [MUI Popup](https://mui.com/base-ui/react-popup/), which uses [Floating UI](https://floating-ui.com/) for positioning. I tried it, but still having the same issue.

@RoelVB, I visited [Floating UI](https://floating-ui.com/) and in its demo, even though the css:zoom style is applied in the BODY, its dropdown is displayed normally and scrolls normally. So, I guess the problem should still be with chromekeepass use of MUI Popper.

**Comment by RoelVB** [comment]
I'm going to repeat myself one last time.

The CKP dropdown mounts outside of the `<body>`. When we mount it inside the `<body>` the positioning is fine, but we have multiple other issues.

I don't think we should create a fix inside CKP for this very specific exception. Unless someone can convince me this is something common.
