### ISSUE TITLE
Basic Authentication issue

### ISSUE THREAD

**Issue by Tassleh0ff** [RoelVB/ChromeKeePass#11]
Hi, I have some problems with basic authentication, seems like ChromeKeePass do not detect BA fields.

OS: Windows 10 Pro 1909
Chrome:  80.0.3987.122
Brave browser: 1.4.95 (based on Chromium 80.0.3987.122)

**Comment by RoelVB** [comment]
Thanks you for reporting. It doesn't support basic auth at the moment.
I'll look into it.

**Comment by RoelVB** [comment]
ChromeKeePass 1.1 should appear in the store any moment now. Please let me know if it works.

You should get a popup when Basic auth is required (unless you have "auto-fill single entry" enabled and only a single entry is found for the specific site):
![image](https://user-images.githubusercontent.com/10999128/76020423-aa11aa80-5f23-11ea-8234-068c26ad4f8c.png)
