### ISSUE TITLE
does not work well with this site

### ISSUE THREAD

**Issue by f1h0** [RoelVB/ChromeKeePass#13]
I tried everything for me. This site does not work well

https://my.moqups.com/login

noticed that the plugin is missing something, it gets confused in the definition of the username and password fields

**Comment by RoelVB** [comment]
Thank you for reporting.
I'll look into it. Unfortunately the site doesn't load at the moment.

**Comment by f1h0** [comment]
The site works with the Russian and German subnets IP just checked.
Really missing the 'exception' setting
For example, I for sites banks and other financial sites
Can this be realized?

**Comment by RoelVB** [comment]
The site is working for me now, so I'll check it out.

What do you mean with exceptions? You want ChromeKeePass to ignore those exceptions?

**Comment by f1h0** [comment]
I want the ChromeKeePass application to ignore the site from the white list that I can make myself.
Is it possible to implement?

**Comment by RoelVB** [comment]
Yes. It is possible, but I'm interested, why would you want/need this?

**Comment by RoelVB** [comment]
Just submitted release 1.1.1 to the Chrome web store. It should appear in a couple of days (after approval)

Please use #14 for your blacklist/whitelist request.

**Comment by f1h0** [comment]
@RoelVB 
If new sites appear again, as in this example, where should I write here? Or create a separate question

**Comment by RoelVB** [comment]
In a new question please.
