### ISSUE TITLE
windows edge 

### ISSUE THREAD

**Issue by wodx521** [RoelVB/ChromeKeePass#17]
It would be nice if it could be published in the windows 10 plugin store

**Comment by RoelVB** [comment]
Thank you. I wasn't aware Microsoft was using a separate store.
I'll look into this.

**Comment by RoelVB** [comment]
It's now in the Edge store.
https://microsoftedge.microsoft.com/addons/detail/edgekeepass/jnhjknbfnclancjpknceboifoegiompf
