### ISSUE TITLE
digitalocean hosting does not work does not see the field

### ISSUE THREAD

**Issue by f1h0** [RoelVB/ChromeKeePass#19]
That is noticed in digitalocean not be substituted for the field user name and password, you can do something?

**Comment by RoelVB** [comment]
I don't see any issues with DigitalOcean.
Could it be that your URL in KeePass is incorrect? It should be https://cloud.digitalocean.com

**Comment by f1h0** [comment]
> I don't see any issues with DigitalOcean.
> Could it be that your URL in KeePass is incorrect? It should be https://cloud.digitalocean.com

Everything already works, great
