### ISSUE TITLE
Redetect keyboard shortcut

### ISSUE THREAD

**Issue by daguej** [RoelVB/ChromeKeePass#20]
It would be nice if there was a keyboard shortcut for redetecting fields.

**Comment by RoelVB** [comment]
Sound like a good idea. I'll look into it.
I would want users to be able to pick their own shortcut.

**Comment by daguej** [comment]
The [commands API](https://developer.chrome.com/apps/commands) is how to do it.

Extensions specify a default key combo, and users can configure shortcut keys at chrome://extensions/shortcuts

**Comment by RoelVB** [comment]
Sorry for the delay.
Just submitted version 1.1.2 to the Chrome store. It could take a couple of days to get approved and published.

**Comment by daguej** [comment]
Awesome, thanks!
