### ISSUE TITLE
ChromeKeePass is defined in the search box

### ISSUE THREAD

**Issue by f1h0** [RoelVB/ChromeKeePass#24]
Here is the problem itself on the ChromeKeePass website is determined in the search field, it is difficult to work interferes
![image](https://user-images.githubusercontent.com/1436880/90424075-3379fb00-e0c6-11ea-9ab9-4d8bd8f98086.png)

site https://kwork.ru/

**Comment by RoelVB** [comment]
That means there's a password field somewhere on that page.
When added, feature #15 makes is possible to ignore this site.

For now I think it's easiest to close dropdown by pressing Esc
