### ISSUE TITLE
Change KeePassHttp Port

### ISSUE THREAD

**Issue by mowfax** [RoelVB/ChromeKeePass#28]
Hello,

I have 2 Instances of KeePass running, one with the default port and one with another. Edge should communicate with the first instance and Chrome with the second, so I have to change the communication port in ChromeKeePass. Is this something that can be implemented as an extension option?

**Comment by RoelVB** [comment]
Of course. I'll add this option when if find some time 😉

**Comment by RoelVB** [comment]
Version 1.2 should be available in the Chrome and Edge store in a couple of days.
