### ISSUE TITLE
Multiple Fields

### ISSUE THREAD

**Issue by moses1701** [RoelVB/ChromeKeePass#3]
I have an account with dell and when logging in there are 2 different fields that appear to be exactly the same. If you go to http://www.dell.com and click sign in you'll be able to see it and take a look. I don't know if anyone else is having problems but I figured I would help with it :)

**Comment by RoelVB** [comment]
I don't understand the problem, could you explain?

There are fields for logging in and fields for creating an account, ChromeKeePass recognizes both as possible login fields, but I don't see any problems with this.

**Comment by moses1701** [comment]
I apologize, I was playing around and it's more of that on the top there is
only a password field.  My name shows up and all it needs
is a password.  That password field isn't being filled in. but the ones
below are.  I hope this helps.

**Comment by moses1701** [comment]
No, I have only ran into it on a page on Dells site.   I'll see if I can
more or less do a layout and try to explain it that way.

<Shows name>
Password: <--- Does not fill password here.


<Screen to sign up>
Password: <---Fills password here

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by RoelVB** [comment]
Could you possible provide a link to the page you're talking about?

**Comment by moses1701** [comment]
I'll see if I can get the exact link that it shows me and let you know either way.

**Comment by moses1701** [comment]
This is the link. It does work when both the E-mail address and password
are both blank.  When you sign in again after you close the
browser it just shows the password field and has your name where the E-mail
address is

https://www.dell.com/Identity/global/LoginOrRegister/98254675-ac6f-47d9-a7e4-4537724f135d?redirectUrl=https%3A%2F%2Fwww.dell.com%2Fen-us%3Flfs%3Dv&c=us&l=en&r=us&s=dhs&cs=19&~ck=mn&feir=1

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by moses1701** [comment]
I don't know if this may help or not. But it looks like that if there's a
password field without a username field near it, it just glosses over it. I
ran into the same problem when I had to login to Gmail. There was a
password field but no place for a username.


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by RoelVB** [comment]
I understand what you mean. I'll try to fix this before the end of the year.

**Comment by moses1701** [comment]
Thank you. I look forward to the updates to this. :)

**Comment by RoelVB** [comment]
Published a new version (1.0.0) (It will be available in the Webstore in max. 60 minutes). The extension should automatically update in your browser.

Happy holidays!

**Comment by moses1701** [comment]
Thanks, I will give it a try and see what happens. Happy holidays to you as
well.
