### ISSUE TITLE
Doesn't detect username on Pekao login page

### ISSUE THREAD

**Issue by cezariuszmarek** [RoelVB/ChromeKeePass#30]
ChromeKeePass doesn't detect user name field on this login page: https://www.pekao24.pl/logowanie
Note: chromeIPass used to work correctly on that page. "Redetect fields" does nothing.

**Comment by cezariuszmarek** [comment]
The same problem on this page: https://www.ipko.pl/secure/ikd3/login.html

**Comment by RoelVB** [comment]
There's no password field on both pages. Most sites use a hidden password field in this case, but your examples don't. You feature request (#31) could solve this.
Unfortunately ChromeKeePass cannot mark this field as a login field. If it did it would mark any textfield as an login field.
