### ISSUE TITLE
Option to fill the current field with username or password

### ISSUE THREAD

**Issue by cezariuszmarek** [RoelVB/ChromeKeePass#31]
Please add a context menu option to fill the current field with the user name or password.
Something similar to chromeIPass:

![image](https://user-images.githubusercontent.com/9655758/94999979-6a946500-05bd-11eb-9073-99146109ed95.png)

**Comment by RoelVB** [comment]
I have a more user friendly method in mind.

**Comment by pseudocoder** [comment]
Second this idea, with the addition that it would be great if this can somehow work without needing to grant full site access, if the URL is still available to the extension.

**Comment by RoelVB** [comment]
This feature is currently in the bèta version.
[ChromeKeePass](https://chromewebstore.google.com/detail/chromekeepass-b%C3%A8ta/ameocahhjkljlabpiajepcipkbcpjpep)
[EdgeKeePass](https://microsoftedge.microsoft.com/addons/detail/edgekeepass-b%C3%A8ta/niekjejailhcgickepdfkhlblegbgecd) (Not yet approved at the time of writing)

**Comment by RoelVB** [comment]
Currently in stable release
