### ISSUE TITLE
Subdomains

### ISSUE THREAD

**Issue by btxtiger** [RoelVB/ChromeKeePass#32]
It seems the extension does not respect subdomains, which makes handling difficult.

**Comment by RoelVB** [comment]
The extension just asks KeePass for credentials matching the current domain.

Are you using KeeWeb? Because I've noticed that KeeWeb ignores subdomains while KeePass doesn't.

**Comment by btxtiger** [comment]
Yes, I am using KeeWeb :)
So it seems to be a KeeWeb issue? Does ChromeKeePass submit the full URL to the keepass client?

**Comment by RoelVB** [comment]
Yes, it sends the full URL to Keepass:
https://github.com/RoelVB/ChromeKeePass/blob/master/src/classes/BackgroundListener.ts#L30-L32

**Comment by btxtiger** [comment]
I have opened this ticket at keeweb: https://github.com/keeweb/keeweb/issues/1750
