### ISSUE TITLE
Login input detection

### ISSUE THREAD

**Issue by btxtiger** [RoelVB/ChromeKeePass#33]
I actually didn't find yet how the login input field detection works. I would be open to contribute some improvements.
There are a couple of sites, where the login field is not recognized, especially if it is behind a modal.

- [ ] [instagram.com](https://www.instagram.com/accounts/login/)
- [ ] [twitter.com](https://twitter.com/account/add)
- [ ] [soundcloud.com](https://soundcloud.com)
- [ ] [songsterr.com](https://www.songsterr.com/a/wa/signin)

You can comment more, if you have the issue.

**Comment by RoelVB** [comment]
Sometime you have to "redetect fields" using the right-click menu or the keyboardshortcut.
I've tested this with Instagram and Twitter and it works fine.

I appropriate you wanting to contribute. This is how the detection flow is now:
The `content_script` calls the `detectFields()` method after the page is loaded:
https://github.com/RoelVB/ChromeKeePass/blob/6826fdf9d2d914b6a2a3b9dce179720b7f7e9a43/src/content_script.ts#L6-L8

Then the `PageControl` class tries to find credential fields:
https://github.com/RoelVB/ChromeKeePass/blob/6826fdf9d2d914b6a2a3b9dce179720b7f7e9a43/src/classes/PageControl.ts#L27-L67
