### ISSUE TITLE
Plugin not working in Brave

### ISSUE THREAD

**Issue by thomascdk** [RoelVB/ChromeKeePass#34]
After the latest Windows 10 feature update (and a reinstall of Windows) the plugin is not working in Brave, but works fine in Chrome and Edge. It says "Something went wrong... Is KeePass running...". On other PCs it works perfectly.

**Comment by RoelVB** [comment]
Brave's `trackers & ads blocking` also blocks connection to localhost.
If you disable this, ChromeKeePass works.

I can not find how to whitelist `localhost` in Brave.

**Comment by RoelVB** [comment]
Found it!
In Brave go to brave://adblock and in the textarea at the bottom, enter this line:
```
@@||localhost^
```

**Comment by thomascdk** [comment]
Fixed it. Very impressive response time!

 

Br,

Thomas
