### ISSUE TITLE
Show password group in dropdown

### ISSUE THREAD

**Issue by btxtiger** [RoelVB/ChromeKeePass#40]
Would be very helpful, if the password group would be shown in the dropdown list.
When I have many login data for the same site, it is hard to identify the correct entry, if I have not written the groupname in the password's title again.
![image](https://user-images.githubusercontent.com/15804690/113607956-2ce6c680-964a-11eb-960b-5bd31ef6bb63.png)

**Comment by RoelVB** [comment]
Unfortunately KeePassHttp doesn't supply a group name.

Maybe there's a modified version out there, I couldn't find it. Preferably the KeeWebHttp plugin also get updates in this case.
I don't feel like it's worth the amount of work to get this added.

But if you add the functionality to both plugins I'll add support into the extension 😉
