### ISSUE TITLE
Extension opens randomly on artstation.com

### ISSUE THREAD

**Issue by Lukardio** [RoelVB/ChromeKeePass#46]
Good day. Today I opened the website artstation.com for the first time, and an autofill window from the extension just popped up in the middle upper part of the screen. This window appeared in the landing page, not in the log in page.

**Comment by RoelVB** [comment]
Sorry for the late reply.

They did something strange with their site design. The login dialog is there and the username fields gets focused, but the dialog is transparent.
The extension normally ignores invisible fields, but their field is technically visible.
