### ISSUE TITLE
Unraid login page not detected

### ISSUE THREAD

**Issue by BoKKeR** [RoelVB/ChromeKeePass#47]
I am using a local network deployed unraid server and I cant get recognition to work, but the form seems fairly simple

```
<div class="form">

                <form action="/login" method="POST">
                    <p>
                        <input name="username" type="text" placeholder="Username" autocapitalize="none" autocomplete="off" autofocus="" required="" title="" style="">
                        <input name="password" type="password" placeholder="Password" required="">
                    </p>
                                        <script type="text/javascript">
                        document.cookie = "cookietest=1";
                        cookieEnabled = document.cookie.indexOf("cookietest=")!=-1;
                        document.cookie = "cookietest=1; expires=Thu, 01-Jan-1970 00:00:01 GMT";
                        if (!cookieEnabled) {
                            document.write('<p class="error">Browser cookie support required for login</p>');
                        }
                    </script>
                    <p>
                        <button type="submit" class="button button--small">Login</button>
                    </p>
                </form>
            </div>
```

**Comment by RoelVB** [comment]
Does it detect the fields if you right-click and choose "Redetect fields" ?

**Comment by BoKKeR** [comment]
No, it does not work then either, is there anything more I can try? I know its not the local network limitation as I can get my router page work.

**Comment by RoelVB** [comment]
Version 1.3 is out with improved field detection.
Can you test to see if this makes a difference?

**Comment by BoKKeR** [comment]
The same problem on 1.3, I get the prompt to fill the screen but it says `no credentials found`

**Comment by RoelVB** [comment]
I thought you meant that the extension didn't detect the fields.
But it seems that it does, but KeeWeb doesn't return any credentials.

The extension just passes the URL to KeeWeb. Could you try the following:
1. In your browser go to chrome://extension
2. Enable developermode (I think it's at the right top)
3. Open the "backgroundpage" for `ChromeKeePass`
4. A DevTools window opens, change it to the "console" tab
5. Now (re)load the Unraid login page

The DevTools will show the URL it requested from KeeWeb.
If this URL shown is incorrect, the extension is doing something wrong. But if it's correct, then it looks like KeeWeb doesn't find the credential entry for some reason.

**Comment by RoelVB** [comment]
Closing this since KeeWeb isn't officially supported by this extension anymore
