### ISSUE TITLE
Provide build instructions

### ISSUE THREAD

**Issue by robin-moser** [RoelVB/ChromeKeePass#5]
Hello,

I really like your app, and in my opinion even in the early 1.0 state it tops most of the other Chrome extensions. It would be cool to provide a build section in the README to describe how to build the extension form source. 
For people like me who aren't familiar with node/webpack, this would be a big help.

Keep up the good work!

**Comment by RoelVB** [comment]
Added the [build instructions](https://github.com/RoelVB/ChromeKeePass/blob/master/Documents/Manuals/Buildinstructions.md).
