### ISSUE TITLE
Not all sites showing all credentials

### ISSUE THREAD

**Issue by McEnnes** [RoelVB/ChromeKeePass#51]
On some sites i have 2 different logins. They are showing in a dropdown at https://www.bol.com/ and on my own Synology server.
On some sites there is only 1 login showing : https://www.ziggo.nl/mail  and https://accounts.spotify.com/

Redetect fields does not solve the issue, neither does left or rightclick in de login field.

**Comment by RoelVB** [comment]
So you're saying the dropdown is shown, but it doesn't contain all logins?
If this is the case, please check the URLs for the entries in KeePass.

ChromeKeePass asks KeePass for logins for the opened url (eg. https://accounts.spotify.com) and KeePass should return all matching logins/entries.

**Comment by McEnnes** [comment]
Sorry i was not very clear with this!
When there is only 1 login showing, there is no dropdown.
There are 2 persons in my household with accounts on Spotify and Ziggo.
Both accounts with login and password are in the Keepass database.

**Comment by McEnnes** [comment]
I took a closer look at this and the problem seems to be solved by adjusting the url for the second account.

**Comment by RoelVB** [comment]
Sorry for the late reply. Good to hear your problem is solved.
