### ISSUE TITLE
not working in latest edge browser

### ISSUE THREAD

**Issue by JD-aus** [RoelVB/ChromeKeePass#53]
I installed the chromekeepass and edgekeepass plugins (which appear to be the same project just under different names?) onto multiple machines. They are all giving me the same results ... what am I doing wrong?

When I launch a website that needs a username & password (such as https://login.live.com/ or https://accounts.google.com/), I can list the available KeePass entries, but when selecting the appropriate entry, the entry is not filled into the inputs.

I have resorted to using KeePassHttp-Connector, which hasn't been updated in 3.5 years but still works ok(ish), but I want to use something that is maintained as I need consistency of service. I am trying to implement KeePass in a small business, but keepassxc doesn't suit our needs, as cloud sync is problematic, but their browser plugin is by far the best I have used in open source products.

Has anyone seen this issue before ? What am I missing?

**Comment by RoelVB** [comment]
First, ChromeKeePass in the version in the Chrome store, EdgeKeePass is the version in Microsoft's store, because Microsoft doesn't allow the name ChromeKeePass.

What's the exact version of Edge you're on? 93.0.961.38 should be the latest (stable build) right now, which works fine for me.

**Comment by JD-aus** [comment]
Version 92.0.902.84 (Official build) (64-bit)

**Comment by JD-aus** [comment]
i just updated to Version 93.0.961.38 (Official build) (64-bit) and still not working. I will spin up a new windows 10 VM for a test to see if it something about my keepass portable edition. interestingly the extension is working prefectly in chome on all machines i have tested it on (but i generally use edge or brave). haven't tested on brave (will do today).

**Comment by RoelVB** [comment]
Could you try selecting an entry with the keyboard (I assume you click it with your mouse)?
You can select an entry with the up/down keys and confirm with Enter (if there's only one entry just press Enter).

**Comment by JD-aus** [comment]
after spinning up a vm and testing with a vanilla edge browser, i am unable to replicate the problem. I will continue to install extensions and apps until it stops working.

**Comment by RoelVB** [comment]
Interesting. There's a change the next release will fix your issue.
I'll let you know when it's published.

**Comment by JD-aus** [comment]
lets hope ... out of curiousity, any plans to capture new usernames and passwords like keepassxc-browser does ? that would be an awesome addition to this plugin...

**Comment by b3belov** [comment]
Hey! I have the same issue.

Edge Version - 93.0.961.47 (Official build) (64-bit)

All works fine if selection confirmed with enter.

**Comment by RoelVB** [comment]
Just submitted version 1.4 of the extension to the stores. Could take a couple of days before it gets approved.
The Edge store normally takes longer than the Chrome store. There's a great change the Edge store approval will not happen this week.

If you don't want to wait for the approval from Microsoft, you could manually install it from [here](https://github.com/RoelVB/ChromeKeePass/releases/tag/1.4).

Please let me know if this resolves your issue.
