### ISSUE TITLE
Intuit login broken

### ISSUE THREAD

**Issue by daguej** [RoelVB/ChromeKeePass#65]
This has started recently -- with the ChromeKeePass extension enabled, the Intuit login page (https://accounts.intuit.com/) doesn't work.  You can enter your email (which does *not* get autofilled), click Sign In, and then it takes you to the "enter your password" step.

The password *does* get autofilled, but you're unable to submit the form.  Clicking Continue or pressing <kbd>Enter</kbd> does nothing.  Manually clearing the prefilled password and pasting or retyping it does not help.  There are no errors in the JS console, nor do I see any XHR requests.  It just doesn't go.

The login page does work after disabling the extension and reloading the page.

**Comment by RoelVB** [comment]
Sorry for the late reply.
I just submitted extension version 1.4.1 to the Chome and Edge stores, this should solve your issue.
(it could take a couple of days for the update to be approved)

**Comment by daguej** [comment]
Unfortunately, it does not appear to be fixed for me.

`chrome://extensions/?id=dphoaaiomekdhacmfoblfblmncpnbahm` shows v1.4.1, but the Intuit login page is still broken; same behavior.
