### ISSUE TITLE
Error web interface router

### ISSUE THREAD

**Issue by rdbox** [RoelVB/ChromeKeePass#67]
The plugin itself adds a login, and spoils the Wi-Fi network setup.

My nerves are already giving up, there are a lot of erroneous substitutions in the fields
![image](https://user-images.githubusercontent.com/18515862/151220773-350d6e93-3861-4883-98d5-1799494b321d.png)

**Comment by RoelVB** [comment]
Technically ChromeKeePass is right detecting those fields.
You should disable the option `Automatically fill credentials if only a single entry is found` to prevent it from automatically filling those fields.

In the future we might get a feature to disable CKP for specific fields/sites. (#15)
