### ISSUE TITLE
Plugin looses connection to KeePassHttp daily

### ISSUE THREAD

**Issue by mks-85** [RoelVB/ChromeKeePass#69]
Hi there,

I've got the problem that my plugin looses connection to KeePassHttp every day, sometimes more than one time a day.

I'm in business environment and Edge is configured by gpo, so mayby there is a option that is responsible for this issue?

Any idea why the problem appears?
![hc_1598](https://user-images.githubusercontent.com/74009667/155084389-8badd906-3da4-4ee2-a92b-71444ffccae7.jpg)

**Comment by RoelVB** [comment]
Do you know if the options also get reset or could you check that?

**Comment by mks-85** [comment]
Options do not get reseted.

When I connect again and use the same key name, I get the following error
![hc_1609](https://user-images.githubusercontent.com/74009667/155682555-605d04a4-3fdc-4a0d-9b7f-1ab81bbfd49b.jpg)
.

**Comment by ipcontrol** [comment]
I encountered the same issue.
Using Ubuntu20.04, with Chrome Version 87.0.4280.141 (Official Build) (64-bit) + ChromeKeePass extension, connecting to locally installed KeePass via KeePassHttp

**Comment by RoelVB** [comment]
I've just submitted version 1.4.2. It could take a couple of days before you get this new version.
Please let me know if this solves your issue.

(It could be that you will have to re-connect just one last time)
