### ISSUE TITLE
Can't connect with KeePass

### ISSUE THREAD

**Issue by KrioB** [RoelVB/ChromeKeePass#74]
Hello,

I can't make connection between Chrome extension (ChromeKeePass) and KeePass plugin (KeePassHttp).
![image](https://user-images.githubusercontent.com/63455106/157680095-7eb00d42-2e82-4c17-b371-4e8014207b17.png)

Another extension has connected so it is rather not a KeePassHttp issue.
| Name | Version |
| -- | -- |
| ChromeKeePass | 1.4.2 |
| KeePassHttp | 1.8.4.2 |
| KeePass | 2.50 (64-bit) |

**Comment by ipcontrol** [comment]
Same issue for me, Getting status endlessly.
It appeared after I upgraded to 1.4.2.
Before the upgrade I had the problem of asking always for new security key in order to connect to KeePass via KeePassHttp

**Comment by RoelVB** [comment]
Thank you both for reporting. I've been able to reproduce it.
After I restart the browser **or** after disabling and re-enabling the extension it works for me.

If you're around, please let me know if this also is the case for you.
I'm working on a fix in the meantime.

**Comment by KrioB** [comment]
Unfortunately the restarting KeePass, plugin, or extension did not help

**Comment by RoelVB** [comment]
I've just submitted 1.4.3 (it will be available after is passes review).
Please let me know if it solves your issue.

If you want you can of course manually install it from the [releases page](https://github.com/RoelVB/ChromeKeePass/releases).
> Note that a manual install will disable automatic updates

**Comment by KrioB** [comment]
Works perfect now
