### ISSUE TITLE
Stuck at "Getting status..." - Problem

### ISSUE THREAD

**Issue by nGgit11** [RoelVB/ChromeKeePass#76]
Tested March 11, 2022 - Stuck at "Getting status..." problem
<img width="523" alt="2022-03-11_163050" src="https://user-images.githubusercontent.com/101392238/157835159-421c0c9c-1cd6-47b2-b10d-917c05008105.png">

ChromeKeePass Version : 1.4.3
KeePass version: 2.50
keepasshttp - [1.8.4.2]
CentBrowser Portable: Chromium 86.0.4240.198
Google Chrome Version 98.0.4758.82
OS: Windows 10 Enterprise LTSC

I did some basic troubleshooting; 
- Enable & disable, install & uninstall the extension - not working
- Cleaning up all the folders associated with KeePass then uninstall then re-install again but still not working.
- Uninstall & Install Chrome - still not working

here's a short screen recording:

https://user-images.githubusercontent.com/101392238/157837682-c64e4dbd-f349-403b-9b28-1e0c184029ec.mp4

**Comment by RoelVB** [comment]
Which version of ChromeKeePass are you using?

**Comment by nGgit11** [comment]
> Which version of ChromeKeePass are you using?

This one 
Version : 1.4.3

**Comment by RoelVB** [comment]
Interesting, thank you for the report. Unfortunately I don't have time to look into this right now.
Hopefully this evening (in about 10 hours). If not, I will look into this the coming weekend

**Comment by nGgit11** [comment]
> Interesting, thank you for the report. Unfortunately I don't have time to look into this right now. Hopefully this evening (in about 10 hours). If not, I will look into this the coming weekend

Thank you also, I hope you can look into this further, If you need more information, please let me know.

**Comment by ipcontrol** [comment]
Uninstalled 1.4.2, installed 1.4.3. but I have the same issue, i.e. still encounter Status: Getting status...

**Comment by RoelVB** [comment]
I've just created and submitted 1.4.4 to the stores.
Please let me know if this resolves your issue.

I feel like such an amateur. I had some spare time I thought I could do a quick fix for #69 
But did this without enough focus, made some stupid mistakes and failed to properly test the changes 😥
> I really want to create some automated tests, but I'm not sure about the best approach for automating KeePass.

**Comment by nGgit11** [comment]
No worries, don't feel bad about yourself, what you feel is okay & normal. there's always a room for improvement. Thank you for taking the time in resolving this. Please know that you have been really helpful to us.
