### ISSUE TITLE
Dropbox Integration Idea

### ISSUE THREAD

**Issue by madaster97** [RoelVB/ChromeKeePass#82]
Hi there,

Any interest in integrating with Dropbox? That's where I currently keep my KeePass files, and it would be awesome if I didn't need to sync files to my desktop just for the local http server.

Would you welcome a PR on this? I've read up on dropbox integration options (OAuth 2.0, embedded file [chooser](https://www.dropbox.com/developers/chooser)).

Thanks,
Adam

Edit: I realize this may be a big project since we'd need to:
- [ ] Consider security of the dropbox integration
- [ ] Load the kdbx into the browser, and consider storing it vs always reloading from dropbox
- [ ] Prompt the user for the key/credential of the database
- [ ] Parse the database, likely with a library like [kdbxweb](https://github.com/keeweb/kdbxweb)

Still, I think it would be doable, fun and helpful to people like me

**Comment by RoelVB** [comment]
ChromeKeePass is meant to interact with the desktop application, not replace it.
I have been thinking about maybe adding this support in the future, but this means the extension should be able to do (alsmost) everything the desktop app does.

Also, next to DropBox it should IMO at least support OneDrive and Google Drive. Preferable also some private cloud solutions like NextCloud.
And loading your KeePass DB file into your browser creates addition security risks. Which means it should be well thought out and tested.

I'm not sure if this is something I want to do. Of course it would take a lot of time to rebuild, but I also need to have time to maintain and support it after.

**Comment by madaster97** [comment]
That is fair. I agree it sounds like a bit much. Closing this
