### ISSUE TITLE
ChromeKeePass - Stopped working all of a sudden

### ISSUE THREAD

**Issue by lakesol** [RoelVB/ChromeKeePass#84]
Hi,

I am on Chrome Version 103.0.5060.114 (Official Build) (64-bit)

All of a sudden the extension has stopped working.

I have check the settings within Keypass and the http plugin.  All seems well.  

I have tried to isolate the issue by installing a similar plugin for firefox which also uses the keypass http plugin.  That works OK.

The plugin is just not seeing the local DB.  

I have tried to (temp) disable local virus protection etc, still no use.

![image](https://user-images.githubusercontent.com/5919075/179705381-64b40441-da46-48af-9285-fa4a512d2ebb.png)

I was wondering if a recent update to Chrome has made communication to local host the issue?

Any thoughts?

Thanks in advance

Lake

**Comment by RoelVB** [comment]
Hi,

Can you maybe give me some more details? What are you seeing? Do you get an error or something?
I cannot reproduce the issues.

**Comment by lakesol** [comment]
Hi @RoelVB 

I don't think there is much more I can tell you.  There is no error messages.  As you can see from the screenshot, no issues are indicated. except now databases listed.  If I click connect nothing happens at all.  No messages/popups etc.

As I mentioned I have isolated the keypass/http side as I got a firefox plugin working.  So it appears like it is somthing to do with my local chrome->localhost communications or the way the plugin is interacting with chrome.

I have tried uninstalling the plugin and reinstalling, but that did not change anything.

Is there any other specific logs/info I can provide what would be helpful?

I am at a bit of a loss to be honest :(

Lake

**Comment by RoelVB** [comment]
I thought the screenshot was of the Firefox plugin you tested.
Your screenshot is not ChromeKeePass, it's some other extension.

**Comment by lakesol** [comment]
Appologoes, wrong screen shot
Try: 
![image](https://user-images.githubusercontent.com/5919075/180074529-d4678da1-2e45-49c0-b76e-fbf60bc69fab.png)

**Comment by RoelVB** [comment]
Sorry for the delay. Could you try the following:


- Put your browser into developer mode (chrome://extension -> "developermode" toggle at the top)

- Open the "backgroundpage" for ChromeKeePass

- Try to connect CKP again

- Check the "Network" tab of the backgroundpage

- Hopefully the request to http://localhost:19455/ shows some useful information.

- If you want you could "Export to HAR" (last icon below the tabbar) and share it here
