### ISSUE TITLE
fields in dropbox are not filled

### ISSUE THREAD

**Issue by f1h0** [RoelVB/ChromeKeePass#86]
I noticed lately on the dropbox site the password fields are not filled in automatically and even by hotkeys.
The extension does not see the password field, you have to manually drive it in

is this solvable?

**Comment by RoelVB** [comment]
Sorry for the late reply. I've looked into this, for some reason Dropbox creates a password field, deletes it and create a new one.
I'm working on a fix for this.

**Comment by RoelVB** [comment]
I've just pushed 1.4.7 to the stores. This should fix this issue.
(It could take a couple of days before you get this update)

**Comment by rdbox** [comment]
@RoelVB 
super I am very happy about this, you quickly solve the difficulties. Thank you very much
