### ISSUE TITLE
Clipboard protection from wiretapping and reading browser Chrome

### ISSUE THREAD

**Issue by f1h0** [RoelVB/ChromeKeePass#87]
I have come across news that makes me very sad.
With new updates, the Chrome browser can read and write to the user's clipboard without the user's permission.

I really hope that these updates that were made to the release will be canceled by the main developer.

The question is, can your plugin protect login and password input? Maybe make an additional encrypted layer?

all details here
https://bugs.chromium.org/p/chromium/issues/detail?id=1334203

**Comment by RoelVB** [comment]
Hi,

I'm not going to try building something into CKP to prevent this (if it's even possible). CKP doesn't do anything with the clipboard, thus isn't directly affected by this. Without using CKP people might copy/paste their username/password into websites, but by using CKP you don't have to. So they never end up on your clipboard
