### ISSUE TITLE
Credentials only detected after redetecting fields

### ISSUE THREAD

**Issue by akuropka** [RoelVB/ChromeKeePass#95]
**System:**
Windows [Version 10.0.22623.1028]
Edge Version 108.0.1462.46 (Official Build) (64-Bit)
EdgeKeePass 1.4.6 from store (side note: store version is not up-to-date)
Alternatively: ChromeKeePass 1.4.7 (same behavior as on EdgeKeePass 1.4.6)

**Step by step:**
1. Open edge, verify that EdgeKeePass is running and connected, credentials are set up in database.
2. Open https://www.mathe-im-advent.de/de/ (happens on some other pages as well) in desktop view
3. Click on Login, hover with mouse over it

**Expected behavior:**
Credentials are filled in

**Recent behavior:**
No credentials are filled in, need to use the "Redetect fields" option to get fields recognized.

**Screencast:**
https://user-images.githubusercontent.com/22570574/206899344-9eba7280-698e-430a-97c4-7f911b0d7444.mp4

**Comment by RoelVB** [comment]
Thank you for reporting and sorry for the late reply.

I'm working on a big rewrite of CKP. I will address this issue after that.

**Comment by RoelVB** [comment]
Just submitted CKP version 2.0 to the stores, which fixes this issue.
It normally gets approved after a few days and will automatically update in your browser.
