### ISSUE TITLE
The plugin doesn't correctly detect username and password fields

### ISSUE THREAD

**Issue by comiluv** [RoelVB/ChromeKeePass#97]
webpage: https://www.qoo10.com/gmkt.inc/Login/Login.aspx
The plugin mistakenly detects password field as username field and OTP field as password field

**Comment by RoelVB** [comment]
Sorry for the very late reply. I though I had replied here.

They have a very strange login form design (from a technical perspective). Support for this will improve in future versions of the extension.

**Comment by sergeevabc** [comment]
Dear @RoelVB, could you be so kind to take a peek at [Rutracker][1]?

At present your extension puts its icon in the site's search field in the header.

Now, click label 'Вход' (means 'Entrance' in Russian) to see login and password fields,
where the icon is really expected. Bitwarden and ProtonPass extensions detect it fine.

![2024-0106-2123 rutracker chromekeepass](https://github.com/RoelVB/ChromeKeePass/assets/373718/a8d1c288-cc8c-4b19-9bdc-ff1fd4678463)


[1]: https://rutracker.org/forum/index.php

**Comment by RoelVB** [comment]
@sergeevabc I've just submitted version 2.0 to the Chrome and Edge stores which would solve your issue.
It's normally approved in a few days and you will automatically get this new version.

If you cannot wait you can get the bèta extension for [Chrome](https://chromewebstore.google.com/detail/chromekeepass-b%C3%A8ta/ameocahhjkljlabpiajepcipkbcpjpep) or [Edge](https://microsoftedge.microsoft.com/addons/detail/edgekeepass-b%C3%A8ta/niekjejailhcgickepdfkhlblegbgecd).
