### ISSUE TITLE
EdgeKeePass Connection problem

### ISSUE THREAD

**Issue by DrFalkKoehler** [RoelVB/ChromeKeePass#98]
EdgeKeePass

System:
Windows 11 Home Version 22H2

Microsoft Edge Version 114.0.1823.55 (Offizielles Build) (64-Bit)

EdgeKeePass Version 1.4.7

KeePassHttp is installed.
KeePass is running, and a password database is opened.
Click on EdgeKeePass icon next to the address bar shows 'Disconnected'.

The following error messages appear:

Connection

Status Something went wrong… is KeePass running and is the KeePassHttp plugin installed?
KeePassHttp address 	localhost 	:	19455

KeePassHttp
***BUG*** System.ArgumentNullException: Der Wert darf nicht NULL sein.
Parametername: s
bei System.Convert.FraomBase64String(String s)

How can I solve the problem?

**Comment by RoelVB** [comment]
What version of KeePass and KeePassHttp are you at?

**Comment by DrFalkKoehler** [comment]
KeePass 2.54

KeePassHttp
I downloaded KeePassHttp on 21 June 2023 with the following Link:
https://github.com/RoelVB/ChromeKeePass/blob/master/Documents/Manuals/KeePassHttp%20installation.md
I do not know where I can find the KeePassHttp version.


911 Greetings from the idyllic Alster Valley in Hamburg - the most beautiful city in the world

Dr. Falk Köhler


DR. FALK KÖHLER PR
Successful PR for market leaders for 35 years
Optimising your PR + Maximising your profit
Best references + Many years of PR practice experience + Highest quality PR
Owner:  Dr. Falk Köhler  Journalist  MBA Master of Business Administration  Chief PR Consultant
Member: DJV German Journalists Association + Hamburg Press Club + MPC Motor Press Club + VdM Association of Motor Journalists
Phone +49 40 61 18 91 30
Mobile +49 172 25 26 945
E-mail ***@***.******@***.***>
www.Dr-Falk-Koehler.de<http://www.dr-falk-koehler.de/>
Ödenweg 59
22397 Hamburg
Germany

Find out the most important facts about me and my PR agency DR. FALK KÖHLER PR on my website:
www.Dr-Falk-Koehler.de<http://www.dr-falk-koehler.de/>


DR. FALK URLAUB & REISEN MAGAZIN
DR. FALK HOLIDAY & TRAVEL MAGAZINE
Dr. Falk Köhler > The best info, tips and deals
Owner:  Dr. Falk Köhler  Editor-in-Chief  Journalist  MBA Master of Business Administration
Member: DJV German Journalists Association + Hamburg Press Club + MPC Motor Press Club + VdM Association of Motor Journalists
E-mail ***@***.******@***.***>
Dr-Falk-Urlaub-Reisen.de<https://dr-falk-urlaub-reisen.de/>
Phone +49 40 611 891 30
Mobile +49 172 25 26 945
Ödenweg 59
22397 Hamburg
Germany

Read the most important facts about my travel magazine DR. FALK URLAUB & REISEN REISEMAGAZIN and about holidays and travel on the website:
https://Dr-Falk-Urlaub-Reisen.de



Von: Roel ***@***.***
Gesendet: Mittwoch, 28. Juni 2023 14:08
An: RoelVB/ChromeKeePass ***@***.***>
Cc: Dr. Falk Koehler ***@***.***>; Author ***@***.***>
Betreff: Re: [RoelVB/ChromeKeePass] EdgeKeePass Connection problem (Issue #98)


What version of KeePass and KeePassHttp are you at?

**Comment by RoelVB** [comment]
Unfortunately I'm unable to reproduce this. Could you try the following:
- Put your browser into developer mode (edge://extensions -> "developermode" toggle at the top)
- Open the "backgroundpage" for ChromeKeePass
- Try to connect CKP again
- Check the "Network" tab of the backgroundpage
- The request to http://localhost:19455/ could shows some additional information
- If you want you could "Export to HAR" (last icon below the tabbar) and share it here

**Comment by RoelVB** [comment]
Closed due to inactivity
